# This file is for testing ansible provisioning
# locally using vagrant.
# To run it, run `vargrant up` in this foler.

Vagrant.configure(2) do |config|

  config.vm.box = "ubuntu/focal64"

  # Disable the new default behavior introduced in Vagrant 1.7, to
  # ensure that all Vagrant machines will use the same SSH key pair.
  # See https://github.com/mitchellh/vagrant/issues/5005
  config.ssh.insert_key = false

  config.vm.provision "ansible" do |ansible|
    ansible.verbose = "v"
    ansible.playbook = "r.yml"
  end
end
